ShoppingCart/ShoppingCart/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShoppingCart.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Biography { get; set; }

        [NotMapped]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        public virtual ICollection<Book> Books { get; set; }
    }
}

ShoppingCart/ShoppingCart/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShoppingCart.Models
{
    public class Book
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Isbn { get; set; }
        public string Synopsis { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public decimal ListPrice { get; set; }
        public decimal SalePrice { get; set; }
        public bool Featured { get; set; }

        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}

ShoppingCart/ShoppingCart/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShoppingCart.Models
{
    public class Cart
    {
        public int Id { get; set; }

        [Index(IsUnique = true)]
        [StringLength(255)]
        public string SessionId { get; set; }

        public virtual ICollection<CartItem> CartItems { get; set; }

    }
}

ShoppingCart/ShoppingCart/Models/CartItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingCart.Models
{
    public class CartItem
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Book Book { get; set; }
    }
}

ShoppingCart/ShoppingCart/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShoppingCart.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Book> Books { get; set; }
    }
}

ShoppingCart/ShoppingCart/ViewModels/AuthorViewModel.cs
using Newtonsoft.Json;

namespace ShoppingCart.ViewModels
{
    public class AuthorViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "fullName")]
        public string FullName { get; set; }

        [JsonProperty(PropertyName = "biography")]
        public string BioGraphy { get; set; }
    }
}

ShoppingCart/ShoppingCart/ViewModels/BookViewModel.cs
using Newtonsoft.Json;

namespace ShoppingCart.ViewModels
{
    public class BookViewModel
    {
        [JsonProperty(PropertyName = "Id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        [JsonProperty(PropertyName = "isbn")]
        public string Isbn { get; set; }

        [JsonProperty(PropertyName = "synopsis")]
        public string Synopsis { get; set; }

        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        [JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

        [JsonProperty(PropertyName = "listPrice")]
        public decimal ListPrice { get; set; }

        [JsonProperty(PropertyName = "salePrice")]
        public decimal SalePrice { get; set; }

        [JsonProperty(PropertyName = "featured")]
        public bool Featured { get; set; }

        [JsonProperty(PropertyName = "savePercentage")]
        public int SavePercentage
        {
            get
            {
                return (int)(100 - (SalePrice / ListPrice * 100));
            }
        }

        [JsonProperty(PropertyName = "author")]
        public virtual AuthorViewModel Author { get; set; }

        [JsonProperty(PropertyName = "category")]
        public virtual CategoryViewModel Category { get; set; }
    }
}

ShoppingCart/ShoppingCart/ViewModels/CartItemViewModel.cs
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;

namespace ShoppingCart.ViewModels
{
    public class CartItemViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "cartId")]
        public int CartId { get; set; }

        [JsonProperty(PropertyName = "bookId")]
        public int BookId { get; set; }

        [JsonProperty(PropertyName = "quantity")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Quantity must be greater than 0")]
        public int Quantity { get; set; }

        [JsonProperty(PropertyName = "book")]
        public BookViewModel Book { get; set; }
    }
}

ShoppingCart/ShoppingCart/ViewModels/CartViewModel.cs
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShoppingCart.ViewModels
{
    public class CartViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "cartItems")]
        public virtual ICollection<CartItemViewModel> CartItems { get; set; }
    }
}

ShoppingCart/ShoppingCart/ViewModels/CategoryViewModel.cs
using Newtonsoft.Json;

namespace ShoppingCart.ViewModels
{
    public class CategoryViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
    }
}

ShoppingCart/ShoppingCart/Controllers/CartsController.cs
using AutoMapper;
using ShoppingCart.Models;
using ShoppingCart.Services;
using ShoppingCart.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    public class CartsController : Controller
    {
        private readonly CartService cartService = new CartService();

        public CartsController()
        {
            AutoMapper.Mapper.Initialize(config =>
            {
                config.CreateMap<Cart, CartViewModel>();
                config.CreateMap<CartItem, CartItemViewModel>();
                config.CreateMap<Book, BookViewModel>();
                config.CreateMap<Author, AuthorViewModel>();
                config.CreateMap<Category, CategoryViewModel>();
            });
        }
        
        [ChildActionOnly]
        public PartialViewResult Summary()
        {
            var cart = cartService.GetBySessionId(HttpContext.Session.SessionID);

            return PartialView(AutoMapper.Mapper.Map<Cart, CartViewModel>(cart));
        }
    }
}

ShoppingCart/ShoppingCart/Controllers/CategoriesController.cs
using ShoppingCart.Models;
using ShoppingCart.Services;
using ShoppingCart.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly CategoryService categoryService = new CategoryService();
        
        public CategoriesController()
        {
            AutoMapper.Mapper.Initialize(config =>
            {
                config.CreateMap<Category, CategoryViewModel>();
            });
        }

        [ChildActionOnly]
        public PartialViewResult Menu(int selectedCategoryId)
        {
            ViewBag.SelectedCategoryId = selectedCategoryId;

            var categories = categoryService.Get();
            return PartialView(AutoMapper.Mapper.Map<List<Category>, List<CategoryViewModel>>(categories));
        }
    }
}

ShoppingCart/ShoppingCart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ShoppingCart/ShoppingCart/Views/Carts/Summary.cshtml
@using ShoppingCart.Extensions
@model ShoppingCart.ViewModels.CartViewModel

<a id="cart" href="@Url.Action("Index", "Carts")" data-bind="click: showCart">
    <span class="glyphicon glyphicon-shopping-cart"></span>
    <span class="badge" data-bind="text: cart.cartItems().length">
        @Model.CartItems.Count
    </span>
</a>
<div class="cart-summary" style="display: none">
    <span data-bind="visible: cart.cartItems().length == 0">
        You currently have no items in your cart.
    </span>
    <div data-bind="visible: cart.cartItems().length > 0">
        <ul>
            <!-- ko foreach: { data: cart.cartItems, afterAdd: fadeIn } -->
            <li data-bind="text: book.title"></li>
            <!-- /ko -->
        </ul>
        <p>
            <strong>Total:</strong> $<span data-bind="text: cart.total"></span>
        </p>
        <br />
        <a href="@Url.Action("Index", "Carts")" class="btn btn-primary">
            View Cart Details
        </a>
    </div>
</div>

<script>
    var cartSummaryData = @Html.HtmlConvertToJson(Model)
</script>

ShoppingCart/ShoppingCart/Views/Categories/Menu.cshtml
@model List<ShoppingCart.ViewModels.CategoryViewModel>

@{ 
    var selectedCategoryId = ViewBag.SelectedCategoryId;
}

<div class="list-group">
    <h4 class="list-group-item-heading">Categories</h4>
    
    @foreach(var category in Model)
    {
        <a href="@Url.Action("Index", "Books", new { categoryId = category.Id })" 
           class="list-group-item @if (selectedCategoryId == category.Id) { @Html.Raw("active") }">
            @category.Name
        </a>
    }
</div>

ShoppingCart/ShoppingCart/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShoppingCart/ShoppingCart/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShoppingCart/ShoppingCart/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Shopping Cart</h1>
    <p class="lead">
        Shop for your favorite books, we've got the best prices.
    </p>
    <p>
        <a href="@Url.Action("About")" class="btn btn-primary btn-lg">Learn More &raquo;</a>
    </p>
</div>

@Html.Action("Featured", "Books")

ShoppingCart/ShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopping Cart", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <div class="navbar-right" id="cart-details">
                    @Html.Action("Summary", "Carts")
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="well well-lg col-lg-3">
            @Html.Action("Menu", "Categories", new { selectedCategoryId = ViewBag.SelectedCategoryId != null ? ViewBag.SelectedCategoryId : 0 })
        </div>
        <div class="col-lg-9">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.Net Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/shoppingCart")
    @RenderSection("scripts", required: false)
</body>
</html>